In [13]:
import numpy as np
from numpy.linalg import *
from scipy import stats

In [2]:
x = np.array([[180, 150],[150, 175],[170, 165],[185, 210]])
x

array([[180, 150],
       [150, 175],
       [170, 165],
       [185, 210]])

In [3]:
y = np.array([[110],[140],[180],[190]])
y

array([[110],
       [140],
       [180],
       [190]])

In [4]:
x.T

array([[180, 150, 170, 185],
       [150, 175, 165, 210]])

In [5]:
mse = inv(x.T @ x) @ x.T @ y
mse

array([[-0.11278259],
       [ 0.99759605]])

In [6]:
sigma = 2*y @ mse.T @ x.T
sigma

array([[28454.47903604, 34685.6223761 , 31994.66768442, 41498.68600403],
       [36214.79150041, 44145.33756958, 40720.48614381, 52816.50945968],
       [46561.87478625, 56758.29116089, 52354.91075633, 67906.94073388],
       [49148.6456077 , 59911.52955871, 55263.51690946, 71679.54855242]])

In [7]:
mle = pinv(x.T @ pinv(sigma) @ x) @ x.T @ pinv(sigma) @ y
mle

array([[0.4526687 ],
       [0.46987478]])

In [8]:
sample = np.array([[175],[170]])
sample

array([[175],
       [170]])

In [9]:
sample.T @ mle

array([[159.09573404]])

In [19]:
scale_1 = sigma @ (mle @ x)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 1)

In [16]:
conf_int = stats.norm.interval(0.95, loc=159.09573404, scale=scale_1)
conf_int

(array([[ -55610.65837545,  -67823.47490447,  -62549.30062476,
          -81176.8342396 ],
        [ -70820.5913144 ,  -86364.1759877 ,  -79651.59054079,
         -103359.36059605],
        [ -91100.50189967, -111085.11076534, -102454.64376217,
         -132936.06240465],
        [ -96170.47954598, -117265.34445975, -108155.40706752,
         -140330.2378568 ]]),
 array([[ 55928.84984353,  68141.66637255,  62867.49209284,
          81495.02570768],
        [ 71138.78278248,  86682.36745578,  79969.78200887,
         103677.55206413],
        [ 91418.69336775, 111403.30223342, 102772.83523025,
         133254.25387273],
        [ 96488.67101406, 117583.53592783, 108473.5985356 ,
         140648.42932488]]))